# travis.yml
# for METROX-CircuitPython
dist: trusty
sudo: false
language: python
python:
    - "3.6"

cache:
    pip: true

install:
  - pip install pylint circuitpython-build-tools

script:
    # lint all the circs 
    pylint --disable=missing-docstring,invalid-name circ/*.py
    # lint all the projects
    pylint --disable=missing-docstring,invalid-name proj/*.py
