# MetroX-CircuitPython travis.yml

dist: trusty
sudo: false
language: python
python:
    - "3.6"

cache:
    pip: true

install:
  - pip install pylint circuitpython-build-tools

script:
    pylint --disable=missing-docstring,invalid-name examples/*.py
