# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: trusty
sudo: false
language: python
python:
    - "3.6"

cache:
    pip: true

install:
  - pip install pylint circuitpython-build-tools

script:
    # loop all circ directories and run pylint within each one
  - pylint CIRC00/*.py
    pylint CIRC01/*.py
    pylint CIRC02/*.py
    pylint CIRC03/*.py
    pylint CIRC04/*.py
    pylint CIRC05/*.py
    pylint CIRC06/*.py
    pylint CIRC07/*.py
    pylint CIRC08/*.py
